/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/dialog/Avatar.vue')['default']
    BaseSettings: typeof import('./components/editor/BaseSettings.vue')['default']
    LoadingScreen: typeof import('./components/LoadingScreen.vue')['default']
    MacMenuBar: typeof import('./components/MacMenuBar.vue')['default']
    MacWindowControls: typeof import('./components/MacWindowControls.vue')['default']
    MenuSettings: typeof import('./components/editor/MenuSettings.vue')['default']
    Message: typeof import('./components/dialog/Message.vue')['default']
    MessageList: typeof import('./components/dialog/MessageList.vue')['default']
    MobileSidebar: typeof import('./components/MobileSidebar.vue')['default']
    ReplyRules: typeof import('./components/editor/ReplyRules.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UrlMatching: typeof import('./components/editor/UrlMatching.vue')['default']
  }
}
